# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: faketpm.spec
files_to_sync:
  - faketpm.spec
  - .packit.yaml

actions:
  # Fetch the specfile from Rawhide, drop any patches and disable rpmautospec
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/faketpm/raw/main/f/faketpm.spec | sed -e '/^Patch:/d' -e '/^%autochangelog$/d' > faketpm.spec\""

srpm_build_deps:
  - bash
  - coreutils
  - curl
  - grep
  - sed

jobs:
- job: copr_build
  trigger: commit
  owner: dcavalca
  project: faketpm
  targets:
    - fedora-all-aarch64
    - fedora-all-i386
    - fedora-all-ppc64le
    - fedora-all-s390x
    - fedora-all-x86_64
